name: pipeline

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: DeLaGuardo/setup-clojure@9.5
        with:
          clj-kondo: 2022.05.31
      - run: clj-kondo --lint src test

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: DeLaGuardo/setup-clojure@9.5
        with:
          cli: 1.10.1.693
      - run: clojure -X:test
